name: Tienda Tuya
on: Tienda Tuya
jobs:
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: rnd_ZF6dDGlZU4FXy2otIOgjamBuHVpu
          github-token: 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
          retries: 20
          wait: 16000
          sleep: 30000