name: Tienda Tuya
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.3.2
        with:
          service_id: 'srv-cg454gqk728m6o4arr1g'
          api_key: 'rnd_ZF6dDGlZU4FXy2otIOgjamBuHVpu'
          clear_cache: false
          wait_deploy: true 