- name: Deploy to Render
  uses: JorgeLNJunior/render-deploy@v1.3.2
  with:
    service_id: ${{ secrets.RENDER_SERVICE_ID }} # required
    api_key: ${{ secrets.RENDER_API_KEY }} # required
    clear_cache: false 
    wait_deploy: true
